In [5]:
import pandas as pd
from pathlib import Path
import os

In [ ]:
if not Path("data").exists():
    os.chdir("..")            # change dir
project_root = Path.cwd()
print(project_root)

d:\Wu\2026\Project Portfolio\003 Project\grocery-demand-estimation

In [58]:
ce_data = pd.read_csv("data/raw/cu_income.csv", header=None)

In [59]:
ce_data.head(10)

,0,1,2,3,4,5,6,7,8
0,Table 1101. Quintiles of income before taxes: ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"(Aggregates in millions of dollars, unless oth...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Item,Aggregate,Lowest\n20\npercent,Second\n20\npercent,Third\n20\npercent,Fourth\n20\npercent,Highest\n20\npercent,NaN,NaN
4,Number of consumer units (in thousands) a/,"135,760","27,139","27,186","26,959","27,205","27,272",NaN,NaN
5,Percent distribution of consumer units,100.0,20.0,20.0,19.9,20.0,20.1,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Consumer unit characteristics (mean values):,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Income before taxes,"$104,207","$16,658","$42,925","$74,474","$121,548","$264,510",NaN,NaN

In [60]:
ce_selected = ce_data.iloc[[3,4,5, 9,51], 0:7]
ce_selected.head()

,0,1,2,3,4,5,6
3,Item,Aggregate,Lowest\n20\npercent,Second\n20\npercent,Third\n20\npercent,Fourth\n20\npercent,Highest\n20\npercent
4,Number of consumer units (in thousands) a/,"135,760","27,139","27,186","26,959","27,205","27,272"
5,Percent distribution of consumer units,100.0,20.0,20.0,19.9,20.0,20.1
9,Income before taxes,"$104,207","$16,658","$42,925","$74,474","$121,548","$264,510"
51,Food at home,"842,257",12.3,15.9,18.7,23.0,30.0

In [84]:
# set column names and row index 
ce = ce_selected.copy()

ce.columns = ce.iloc[0]
ce = ce.iloc[1:]
ce.columns.name = None

ce = ce.set_index(ce.columns[0])
ce.index.name = None

ce

,Aggregate,Lowest\n20\npercent,Second\n20\npercent,Third\n20\npercent,Fourth\n20\npercent,Highest\n20\npercent
Number of consumer units (in thousands) a/,"135,760","27,139","27,186","26,959","27,205","27,272"
Percent distribution of consumer units,100.0,20.0,20.0,19.9,20.0,20.1
Income before taxes,"$104,207","$16,658","$42,925","$74,474","$121,548","$264,510"
Food at home,"842,257",12.3,15.9,18.7,23.0,30.0

In [85]:
ce.columns

Index(['Aggregate', 'Lowest\n20\npercent', 'Second\n20\npercent',
       'Third\n20\npercent', 'Fourth\n20\npercent', 'Highest\n20\npercent'],
      dtype='str')

In [91]:
ce.index

Index(['Number of consumer units (in thousands) a/ ',
       'Percent distribution of consumer units', 'Income before taxes',
       'Food at home'],
      dtype='str')

In [93]:
# rename columns and rows
ce = ce.rename(columns={
    "Lowest\n20\npercent": "lowest20pct",
    "Second\n20\npercent": "second20pct",
    "Third\n20\npercent": "third20pct",
    "Fourth\n20\npercent": "fourth20pct",
    "Highest\n20\npercent": "highest20pct"
})

ce = ce.rename(index={
    'Number of consumer units (in thousands) a/ ': 'num_cu',
    'Percent distribution of consumer units': 'pct_cu',
    'Income before taxes': 'income_mean',
    'Food at home': 'grocery'
})
ce

,Aggregate,lowest20pct,second20pct,third20pct,fourth20pct,highest20pct
num_cu,"135,760","27,139","27,186","26,959","27,205","27,272"
pct_cu,100.0,20.0,20.0,19.9,20.0,20.1
income_mean,"$104,207","$16,658","$42,925","$74,474","$121,548","$264,510"
grocery,"842,257",12.3,15.9,18.7,23.0,30.0